image: docker.staging/centos7-slurm-sbt:18.08.8-1.2.1

stages:
  - build
  - test
  - package
  - deploy

before_script:
  - uname
  - pwd 
  - which sbt 
  - hostname
  - sed -i 's/ernie/localhost/g' /etc/slurm/slurm.conf
  - /usr/local/bin/docker-entrypoint.sh
  - supervisorctl status

sbt-unit-test:
  script:
    - curl http://10.6.38.2:31080/artifactory/generic/org.gc/testdata/testdata-1.tar | tar xf - 2> /dev/null
    - GC_TESTFOLDER=testdata sbt -Dsbt.repository.config=repositories -Dsbt.override.build.repos=true -batch 'coverage' 'test' 'coverageReport' 'coverageAggregate'
  artifacts:
    reports:
      junit:
       - '*/target/test-reports/*xml'
    paths:
      - target/scala-2.12/scoverage-report/*
  coverage: '/Coverage was \[(\d+\.\d+)\]/'
  except:
    - master

sbt-it-test:
  script:
    - curl http://10.6.38.2:31080/artifactory/generic/org.gc/testdata/testdata-1.tar | tar xf - 2> /dev/null
    - GC_TESTFOLDER=testdata sbt -Dsbt.repository.config=repositories -Dsbt.override.build.repos=true -batch 'coverage' 'it:test' 'coverageReport' 'coverageAggregate'
  artifacts:
    reports:
      junit:
       - '*/target/test-reports/*xml'
    paths:
      - target/scala-2.12/scoverage-report/*
  coverage: '/Coverage was \[(\d+\.\d+)\]/'
  except:
    - master

sbt-unit-it-test:
  script:
    - curl http://10.6.38.2:31080/artifactory/generic/org.gc/testdata/testdata-1.tar | tar xf - 2> /dev/null
    - GC_TESTFOLDER=testdata sbt -Dsbt.repository.config=repositories -Dsbt.override.build.repos=true -batch 'coverage' 'test' 'it:test' 'coverageReport' 'coverageAggregate'
  artifacts:
    reports:
      junit:
       - '*/target/test-reports/*xml'
    paths:
      - target/scala-2.12/scoverage-report/*
  coverage: '/Coverage was \[(\d+\.\d+)\]/'  
  only:
    - masterdisable

sbt-package:
  stage: package
  script:
    - sbt -Dsbt.repository.config=repositories -Dsbt.override.build.repos=true -batch 'pipelineExecutor/universal:packageZipTarball'
  artifacts:
    expire_in: '1 day'
    paths:
      - pipeline-executor/target/universal/*gz
  only:
    - masterdisable

deploy-to-staging:
  stage: deploy
  before_script: 
   - echo -n ''
  script: |
     mkdir build
     //  ARCHIVE=$(ls pipeline-executor/target/universal/*gz)
     ARCHIVE=/home/ibartha2/pipeline-executor-3-127-gccc364b.tgz
     VERSION=$(basename $ARCHIVE | awk -F- '{print $3"-"$4"-"$5}' | awk -F. '{print $1}' )

     tar xf $ARCHIVE -C build --strip-components 1
     cp docker/staging/resources/* build/resources/

     cd build
     docker build -f ../docker/staging/Dockerfile -t docker.staging/gc/pipeline:$VERSION .
     docker push docker.staging/gc/pipeline:$VERSION
     cd ..

     TEMPLATE=kubernetes.deployment.yml
     cat $TEMPLATE | sed "s/{{IMAGEVERSION}}/$VERSION/g" | kubectl apply -f -
  tags:
    - shell-runner
  # dependencies:
  #   - sbt-package
  only:
    - master